// 買取業者18社の「箱なし・付属品なし」「傷・使用感・破損」「買取不可品」「財布・靴の取扱」に関する公式記載。
// 各社公式サイトの該当ページを2026-09-22に取得し、引用文はホスト側でcurl+正規化substring照合(全件一致)。
// quote は公式ページの原文(要約・改変なし)。q は該当FAQの設問(ある場合)。source は出典ページ種別(外部リンクは設置しない)。

export type PolicyQuote = { status: "ok" | "not_found"; q: string | null; quote: string | null; source: string | null };
export type DealerPolicy = {
  slug: string;
  accessories: PolicyQuote; // 箱・付属品なし
  damaged: PolicyQuote; // 傷・汚れ・使用感・破損
  notAccepted: PolicyQuote; // 買取不可・お断り
  wallet: "yes" | "no" | "not_found";
  shoes: "yes" | "no" | "not_found";
  itemsQuote: string | null; // 取扱品目の公式記載
  confirmedAt: string;
};

export const DEALER_POLICIES: DealerPolicy[] = [
  {
    slug: "brandoff",
    accessories: { status: "ok", q: "箱や保存袋がない本体のみですが、価格は下がりますか？", quote: "本体のみでも買取いたします。安心してお持ちください。", source: "よくある質問" },
    damaged: { status: "ok", q: "内側がベタついていたり、剥がれているバッグも売れますか？", quote: "状態にもよってしまいますが買取可能です。", source: "よくある質問" },
    notAccepted: { status: "ok", q: null, quote: "不正品の疑いがあると判断された場合、売買契約成立の前後にかかわらず所轄警察署にその旨を申告するとともに法的対応をとらせていただく場合があります。", source: "買取規約・ルール" },
    wallet: "yes",
    shoes: "yes",
    itemsQuote: "バッグ以外にも、財布、アクセサリー、靴、アパレルなど、ルイヴィトン製品なら査定対象です。",
    confirmedAt: "2026-09-22",
  },
  {
    slug: "ecostyle",
    accessories: { status: "ok", q: "付属品はなくても買取してもらえますか？", quote: "もちろん買取可能です。（一部、シルバーブランドや高級時計に関しては例外もございますのでお問い合わせください。）", source: "よくある質問" },
    damaged: { status: "ok", q: null, quote: "シミや汚れが著しいものはハイブランドを除き買取できません。", source: "買取できないもの一覧" },
    notAccepted: { status: "ok", q: null, quote: "有名ブランドの商標登録されたものを模したものは買取できません。", source: "買取できないもの一覧" },
    wallet: "yes",
    shoes: "yes",
    itemsQuote: "スニーカーやブーツ、革靴まで幅広く買取しております。使用感のあるお品物もぜひお売りください。",
    confirmedAt: "2026-09-22",
  },
  {
    slug: "komehyo",
    accessories: { status: "ok", q: "保証書などがなくても買い取ってもらえますか？", quote: "一部のブランドや特定の品物を除き、基本的には買取り可能です。", source: "よくある質問" },
    damaged: { status: "ok", q: "どんな状態でも買取可能ですか？", quote: "明らかな破損、ひどい汚れや劣化の激しい品物以外は、買取可能でございます。", source: "よくある質問" },
    notAccepted: { status: "ok", q: null, quote: "また、「シミ・汚れ・破れ」などがある品物や当社で販売できないと判断させていただいた品物も、お値段をお付けすることができません。", source: "よくある質問" },
    wallet: "yes",
    shoes: "yes",
    itemsQuote: "またアウター、トップス、ボトムスやブーツ、スニーカー等、様々なアイテムの買取も承っております。",
    confirmedAt: "2026-09-22",
  },
  {
    slug: "first-class",
    accessories: { status: "ok", q: "箱や保証書をなくしたからむりですか？", quote: "ということを心配される方も多數いらっしゃいます。結論から申し上げますと、『ほぼ全てのブランド品には価値があります』。", source: "初めての方へ" },
    damaged: { status: "ok", q: null, quote: "過去に１度だけお断りしたバッグがありましたが、そのバッグは内部が腐食していて持ち手が外れているようなバッグでした。", source: "初めての方へ" },
    notAccepted: { status: "ok", q: null, quote: "ショッピングローン残高がある商品はいかなる場合でも買取できません。", source: "買取規約・ルール" },
    wallet: "yes",
    shoes: "yes",
    itemsQuote: "また、多くお問い合わせをいただくものとして、ブランド服や靴などのアパレル関連の買取もご用命をいただいております。",
    confirmedAt: "2026-09-22",
  },
  {
    slug: "kaitori-daikichi",
    accessories: { status: "ok", q: "付属品がないのですが、買い取りしてもらえますか？", quote: "はい、問題ございません。宝石であれば鑑定書や鑑別書、腕時計であれば保証書などの付属品がある場合もございますが、失くされていても、精一杯の金額でお買取りさせていただいております！", source: "よくある質問" },
    damaged: { status: "ok", q: null, quote: "ボロボロの物でもお買取りをしておりますのでご安心ください。例えばチャックが壊れてしまった財布や中がべたべたになってしまったバッグ等もお買取できます。", source: "買取案内ページ" },
    notAccepted: { status: "ok", q: null, quote: "※一部買取不可商品もございますので詳しくはお問い合わせください。", source: "買取案内ページ" },
    wallet: "yes",
    shoes: "yes",
    itemsQuote: "バーバリー、エルメス、ルイ・ヴィトン、フェラガモのスカーフや靴、ベルトからビキューナのジャケット、ロロピアーナのコートやモンクレールのダウン、ルブタンの靴やヴィトンのジャケットなど。",
    confirmedAt: "2026-09-22",
  },
  {
    slug: "ikuraya",
    accessories: { status: "ok", q: "箱や保証書がなくても査定できますか？", quote: "はい、査定可能です。付属品がある場合は買取額が上がる傾向にありますが、本体のみでもブランドやモデルによっては高額買取が期待できます。", source: "よくある質問" },
    damaged: { status: "ok", q: "汚れや傷があるブランド品でも買取できますか？", quote: "はい、可能です。角スレ、シミ、ファスナー不良などがあっても需要のあるモデルは高額査定になる場合があります。状態によりクリーニングや修理が前提になるケースもあります。", source: "よくある質問" },
    notAccepted: { status: "ok", q: "ノーブランド品は買取できますか？", quote: "基本的には対象外ですが、一部デザイン性や素材価値の高い商品はお取り扱いできる場合があります。事前にお問い合わせください。", source: "よくある質問" },
    wallet: "yes",
    shoes: "not_found",
    itemsQuote: "ルイ・ヴィトン、シャネル、エルメス、グッチなどのバッグ・財布・小物をはじめ、洋服やアクセサリー、限定品まで幅広くお取り扱いしています。",
    confirmedAt: "2026-09-22",
  },
  {
    slug: "librand",
    accessories: { status: "not_found", q: null, quote: null, source: null },
    damaged: { status: "ok", q: null, quote: "傷や汚れなど使用感があるバッグでもリブランなら満足いただける買取価格をご提示いたします。", source: "買取案内ページ" },
    notAccepted: { status: "ok", q: null, quote: "当社が不正な商品（偽造品・コピー商品、類似商品、誤認を招く商品又は真物ではない商品、盗品など）と判断した場合、着払いで返送するものとします。", source: "買取案内ページ" },
    wallet: "not_found",
    shoes: "not_found",
    itemsQuote: "ブランド品、腕時計、アクセサリー、金製品、ダイヤモンドなど。",
    confirmedAt: "2026-09-22",
  },
  {
    slug: "reclo",
    accessories: { status: "ok", q: null, quote: "弊社では付属品のみの買取は行なっておりませんが、商品と一緒に売却していただけますと、高価買取が可能です。商品により付属品は違いますが、例えば、箱やギャランティカード（保証書）、バッグ付属のベルトなどがあります。", source: "買取案内ページ" },
    damaged: { status: "ok", q: null, quote: "古く状態の悪い商品についても買取実績がございます。", source: "買取案内ページ" },
    notAccepted: { status: "ok", q: null, quote: "偽造品、盗難品その他第三者の権利を侵害している又は侵害していると疑われるもの", source: "買取案内ページ" },
    wallet: "yes",
    shoes: "yes",
    itemsQuote: "ブランド品（バッグ・小物・時計・靴・アパレル・アクセサリー）や貴金属等の幅広いアイテムの買取を行っております。",
    confirmedAt: "2026-09-22",
  },
  {
    slug: "uriel",
    accessories: { status: "ok", q: "箱やギャランティーカードを紛失してしまいましたが、査定に影響ありますか？", quote: "付属品が揃っていた方が査定額はアップする可能性がありますが、無い場合でも買取可能です。ただし、お品物によっては買取できない場合もございますので、予めご了承ください。", source: "買取案内ページ" },
    damaged: { status: "ok", q: "汚れていたり、破損している古いバッグは買い取ってもらえませんか？", quote: "お品物の状態を直接拝見させていただけると、買取可能かどうか判断できます。ぜひ、無料査定をご利用ください。", source: "買取案内ページ" },
    notAccepted: { status: "ok", q: null, quote: "第三者の著作権、商標権、意匠権、その他知的財産権を侵害する物", source: "買取規約・ルール" },
    wallet: "yes",
    shoes: "yes",
    itemsQuote: "バッグや財布、時計やアクセサリー、お洋服や靴など、どのようなブランド品でも査定させていただきます。状態よって買取ができない物もございますので、まずは一度お問合せください。",
    confirmedAt: "2026-09-22",
  },
  {
    slug: "tifana",
    accessories: { status: "ok", q: null, quote: "付属品がなくても問題ございません。ブランドによってはお値段が少し変動する場合がありますが、箱やその他の付属品が無い靴も取り扱っております。", source: "買取案内ページ" },
    damaged: { status: "ok", q: null, quote: "ティファナでは動かない、壊れた腕時計もお買取させて頂きます。またヴィンテージ品などは状態が悪くても、お買取させて頂いた実績が多数ございます。", source: "買取案内ページ" },
    notAccepted: { status: "ok", q: null, quote: "※その他、リユースが難しいと鑑定士が判断したお品物はお買取することが出来ません。ご了承ください。", source: "買取案内ページ" },
    wallet: "yes",
    shoes: "yes",
    itemsQuote: "リサイクルショップ ティファナではお洋服(古着)、家電、靴、ブランド品、貴金属、骨董品など幅広くお取り扱い！",
    confirmedAt: "2026-09-22",
  },
  {
    slug: "akinaya",
    accessories: { status: "not_found", q: null, quote: null, source: null },
    damaged: { status: "ok", q: null, quote: "状態が悪くてもお買取可能な場合がございます。", source: "よくある質問" },
    notAccepted: { status: "not_found", q: null, quote: null, source: null },
    wallet: "yes",
    shoes: "yes",
    itemsQuote: "パンプス、サンダル、スニーカー、ブーツ、革靴など",
    confirmedAt: "2026-09-22",
  },
  {
    slug: "brandoule",
    accessories: { status: "ok", q: null, quote: "付属品がないお品物も査定対象となります。付属品がある場合、査定金額がUPする場合がございますので、お持ちでしたら合わせてご依頼ください。", source: "よくある質問" },
    damaged: { status: "ok", q: null, quote: "壊れたお品物に関しては基本的に買取ができかねてしまいます。ご了承くださいませ。", source: "よくある質問" },
    notAccepted: { status: "ok", q: null, quote: "汚れ、破れ、痛みの著しい物・使用された下着類、コピー商品等は買取をお断りさせて頂いております。お買取の判断は、弊社の買取基準を基に判断させて頂いております。", source: "よくある質問" },
    wallet: "yes",
    shoes: "yes",
    itemsQuote: "シューズ(サンダル・パンプス・ブーツ等)、帽子(キャップ・ハット等)、バッグ(トートバッグ・ショルダーバッグ等)、ファッション雑貨(ストール・財布・アクセサリー等)。",
    confirmedAt: "2026-09-22",
  },
  {
    slug: "netoff",
    accessories: { status: "ok", q: "買取案内「こんなものでも買取OK!」の一覧項目", quote: "鑑定書・保証書・付属品・箱がない", source: "買取案内ページ" },
    damaged: { status: "ok", q: "買取案内「こんなものでも買取OK!」の一覧項目", quote: "ひっかきキズ・こすった痕がある", source: "買取案内ページ" },
    notAccepted: { status: "ok", q: null, quote: "盗品の疑いがある商品や、当社の買取基準に該当しない商品は、買取をお断りする場合があります。あらかじめご了承ください。", source: "よくある質問" },
    wallet: "yes",
    shoes: "yes",
    itemsQuote: "ブランドバッグ・財布・小物",
    confirmedAt: "2026-09-22",
  },
  {
    slug: "kindal",
    accessories: { status: "ok", q: null, quote: "タグ・箱・説明書などの状態の良い付属品がついていると査定額がUPする可能性が高いです。", source: "買取案内ページ" },
    damaged: { status: "ok", q: null, quote: "■使用に難をきたす大きなダメージがあるもの", source: "買取規約・ルール" },
    notAccepted: { status: "ok", q: null, quote: "偽造品・コピーアイテム / 状態が著しく悪いもの / ネーム刺繍が入ったジャケット・スーツ / 電池切れの時計 / ニーズが低下したデザインのアイテム / ブランドタグ・刻印が確認できないもの /ノーブランドのもの", source: "買取規約・ルール" },
    wallet: "yes",
    shoes: "yes",
    itemsQuote: "洋服・バッグ・時計・靴・財布・アクセサリー・服飾小物などアパレル用品全般をお買取しております。",
    confirmedAt: "2026-09-22",
  },
  {
    slug: "manekiya",
    accessories: { status: "ok", q: null, quote: "箱や鍵、ギャランティーカードなどの付属品が有ればプラスの要因となります。", source: "よくある質問" },
    damaged: { status: "ok", q: null, quote: "汚れや埃、カビなどがございましても買取は可能です。", source: "よくある質問" },
    notAccepted: { status: "ok", q: null, quote: "法律に違反するお買取は出来かねます。", source: "よくある質問" },
    wallet: "yes",
    shoes: "yes",
    itemsQuote: "使わなくなったブランド財布の買取をお考えなら、まねきやにお任せください。",
    confirmedAt: "2026-09-22",
  },
  {
    slug: "nanboya",
    accessories: { status: "ok", q: null, quote: "保証書や保存袋などの付属品がなく、お品物のみでも買取しておりますのでご安心ください。", source: "よくある質問" },
    damaged: { status: "ok", q: null, quote: "汚れや破れがあるお品物も査定対象で、金額のご案内ができれば買い取りの対象です。", source: "よくある質問" },
    notAccepted: { status: "ok", q: null, quote: "大変申し訳ございませんが、ブランド問わず、空き箱やショッパー（紙袋）は買取できかねます。", source: "よくある質問" },
    wallet: "yes",
    shoes: "yes",
    itemsQuote: "「なんぼや」では、使用、未使用問わず、靴もお洋服も査定対象でございますので、ご安心ください。",
    confirmedAt: "2026-09-22",
  },
  {
    slug: "ribla",
    accessories: { status: "ok", q: null, quote: "本体のみでもお買取り可能です。保存袋・箱・ギャランティカードなどの付属品がない状態でも査定対象となりますのでご安心ください。", source: "買取案内ページ" },
    damaged: { status: "ok", q: null, quote: "ダメージや汚れのあるお品物も買取可能です。", source: "よくある質問" },
    notAccepted: { status: "ok", q: null, quote: "申し訳ございませんが、ノーブランドやファストファッションの買取はご遠慮いただいております。", source: "よくある質問" },
    wallet: "yes",
    shoes: "yes",
    itemsQuote: "洋服の他に服飾雑貨（バッグ、靴、腕時計、帽子、アクセサリーなど）も買取可能です。",
    confirmedAt: "2026-09-22",
  },
  {
    slug: "the-gold",
    accessories: { status: "ok", q: "鑑定書がない宝石、箱や保証書がないブランド品でも買い取りしてもらえますか？", quote: "はい、全く問題ございません。鑑定書・保証書等がないお品物でも、専門査定士がお品物の価値をしっかりお調べして、金額をご提示しますので、安心してお任せください。", source: "よくある質問" },
    damaged: { status: "ok", q: null, quote: "はい、破損などが原因で他店でお値段が付かなかったお品物でも、当社でお買取りできる場合がございます。特定ブランドの場合は、多大な破損があっても取扱い可能ですので、まずはお気軽にご相談ください。", source: "よくある質問" },
    notAccepted: { status: "ok", q: null, quote: "※商品の状態や当社規定等により、お取扱いできない場合もございます。", source: "買取案内ページ" },
    wallet: "yes",
    shoes: "yes",
    itemsQuote: "洋服や靴などのアパレル品は、エルメスやルイ・ヴィトンなど一部のブランドで取扱いが可能です。",
    confirmedAt: "2026-09-22",
  },
];

export const policyOf = (slug: string) => DEALER_POLICIES.find((p) => p.slug === slug);
